# Generated by Django 4.1.5 on 2023-04-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pseudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verticals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('pseudos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pseudos.pseudos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('section_type', models.CharField(choices=[('basic', 'Basic'), ('summary', 'Summary'), ('experience', 'Experience'), ('education', 'Education'), ('skill', 'Skill'), ('certificate', 'Certificate'), ('hobby', 'Hobby'), ('link', 'Link'), ('other', 'Other')], max_length=250)),
                ('value', models.JSONField(blank=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
