# Generated by Django 4.1.5 on 2023-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verticals',
            name='identity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
