# Generated by Django 4.1.5 on 2023-05-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_profile_vertical_team_verticals'),
        ('pseudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'default_permissions': ()},
        ),
        migrations.AddField(
            model_name='verticals',
            name='identity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
        migrations.CreateModel(
            name='GenericSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'db_table': 'generic_skills',
                'default_permissions': (),
                'unique_together': {('name', 'type', 'company')},
            },
        ),
        migrations.AddField(
            model_name='skills',
            name='generic_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.genericskills'),
        ),
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together={('vertical', 'generic_skill')},
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name',
        ),
    ]
