# Generated by Django 4.1.5 on 2023-04-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_groups'),
        ('pseudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudos',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AddField(
            model_name='resumesections',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AddField(
            model_name='verticals',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
    ]
