# Generated by Django 4.1.5 on 2023-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0003_sectionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='verticals',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
