# Generated by Django 4.1.5 on 2023-04-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0003_certificate_education_experience_language_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='vertical',
        ),
    ]
