# Generated by Django 4.1.5 on 2023-04-06 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0004_remove_resume_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='language',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='links',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='othersection',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='verticals',
            name='type',
        ),
        migrations.AddField(
            model_name='certificate',
            name='verticals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='education',
            name='verticals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='experience',
            name='verticals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='language',
            name='verticals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='links',
            name='verticals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='othersection',
            name='verticals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='skills',
            name='verticals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='verticals',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verticals',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='portfolio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='section_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('summary', 'Summary'), ('experience', 'Experience'), ('education', 'Education'), ('skill', 'Skill'), ('certificate', 'Certificate'), ('hobby', 'Hobby'), ('link', 'Link'), ('other', 'Other')], default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verticals',
            name='show_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verticals',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='verticals',
            name='pseudos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.pseudos'),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
