# Generated by Django 4.1.5 on 2023-04-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0005_remove_certificate_resume_remove_education_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verticals',
            name='section_type',
        ),
    ]
