# Generated by Django 4.1.5 on 2023-04-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0006_remove_verticals_section_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verticals',
            old_name='pseudos',
            new_name='pseudo',
        ),
        migrations.RemoveField(
            model_name='verticals',
            name='company',
        ),
    ]
