# Generated by Django 4.1.5 on 2023-04-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0007_rename_pseudos_verticals_pseudo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verticals',
            name='title',
        ),
        migrations.AddField(
            model_name='verticals',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
