# Generated by Django 4.1.5 on 2023-04-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0008_remove_verticals_title_verticals_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='name',
        ),
    ]
