# Generated by Django 4.1.5 on 2023-04-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0009_rename_skill_level_skills_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='verticals',
            new_name='vertical',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='verticals',
            new_name='vertical',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='verticals',
            new_name='vertical',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='verticals',
            new_name='vertical',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='verticals',
            new_name='vertical',
        ),
        migrations.RenameField(
            model_name='othersection',
            old_name='verticals',
            new_name='vertical',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='verticals',
            new_name='vertical',
        ),
    ]
