# Generated by Django 4.1.5 on 2023-04-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0010_rename_verticals_certificate_vertical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
