# Generated by Django 4.1.5 on 2023-04-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0012_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.TextField()),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
