# Generated by Django 4.1.5 on 2023-04-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0013_coverletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals'),
        ),
    ]
