# Generated by Django 4.1.5 on 2023-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0014_alter_coverletter_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='verticals',
            name='identity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
