# Generated by Django 4.1.5 on 2023-04-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0016_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verticals',
            name='identity',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
