# Generated by Django 4.1.5 on 2023-02-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=2000)),
                ('company_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('job_source', models.CharField(max_length=2000)),
                ('job_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('address', models.CharField(max_length=2000)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('tech_keywords', models.TextField(blank=True, null=True)),
                ('job_posted_date', models.DateTimeField(blank=True, null=True)),
                ('job_source_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('job_status', models.IntegerField(choices=[(0, 'To Apply'), (1, 'Applied'), (2, 'Hired'), (3, 'Rejected'), (4, 'Warm Lead'), (5, 'Hot Lead')], default=0)),
            ],
            options={
                'db_table': 'job_detail',
                'ordering': ['-job_posted_date'],
                'unique_together': {('company_name', 'job_title', 'job_source_url')},
            },
        ),
        migrations.CreateModel(
            name='AppliedJobStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_by', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='applied by')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobdetail')),
            ],
            options={
                'db_table': 'applied_job_status',
                'ordering': ['id'],
            },
        ),
    ]
