# Generated by Django 4.1.5 on 2023-03-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistjobs',
            old_name='compnay_name',
            new_name='company_name',
        ),
    ]
