# Generated by Django 4.1.5 on 2023-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_alter_appliedjobstatus_applied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='job_status',
            field=models.IntegerField(choices=[(0, 'To Apply'), (1, 'Applied'), (2, 'Hired'), (3, 'Rejected'), (4, 'Cold Lead'), (5, 'Warm Lead'), (6, 'Hot Lead'), (7, 'Prospect')], default=0),
        ),
    ]
