# Generated by Django 4.1.5 on 2023-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_rename_compnay_name_blacklistjobs_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
