# Generated by Django 4.1.5 on 2023-03-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_jobdetail_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='job_status',
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='job_status',
            field=models.IntegerField(choices=[(0, 'To Apply'), (1, 'Applied'), (2, 'Hired'), (3, 'Rejected'), (4, 'Cold Lead'), (5, 'Warm Lead'), (6, 'Hot Lead'), (7, 'Prospect')], default=0),
        ),
        migrations.AlterField(
            model_name='appliedjobstatus',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobdetail'),
        ),
    ]
