# Generated by Django 4.1.5 on 2023-02-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_alter_jobdetail_job_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobdetail',
            unique_together={('company_name', 'job_title')},
        ),
    ]
