# Generated by Django 4.1.5 on 2023-03-09 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0004_remove_jobdetail_job_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedjobstatus',
            unique_together={('applied_by', 'job')},
        ),
    ]
