# Generated by Django 4.1.5 on 2023-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_alter_appliedjobstatus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
