# Generated by Django 4.1.5 on 2023-04-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0014_alter_coverletter_vertical'),
        ('job_portal', '0006_jobdetail_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobstatus',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pseudos.verticals'),
        ),
    ]
