# Generated by Django 4.1.5 on 2023-04-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0001_initial'),
        ('job_portal', '0007_appliedjobstatus_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobstatus',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pseudos.verticals'),
        ),
    ]
