# Generated by Django 4.1.5 on 2023-06-15 10:32

from django.db import migrations, models

from job_portal.models import AppliedJobStatus, JobDetail


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0008_alter_jobarchive_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_applied',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jobdetail',
            unique_together={('company_name', 'job_title', 'job_applied')},
        ),
    ]

try:
    job_ids = AppliedJobStatus.objects.values_list("job_id", flat=True)
    qs = JobDetail.objects.filter(id__in=job_ids)
    qs.count()
    for x in qs:
        x.job_applied = x.id
        x.save()
except Exception as e:
    print("Error in updating job fields => ", str(e))
