# Generated by Django 4.1.5 on 2023-04-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0008_appliedjobstatus_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobstatus',
            name='vertical',
        ),
    ]
