# Generated by Django 4.1.5 on 2023-04-20 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0002_verticals_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0008_appliedjobstatus_vertical'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedjobstatus',
            unique_together={('applied_by', 'job', 'vertical')},
        ),
    ]
