# Generated by Django 4.1.5 on 2023-04-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0001_initial'),
        ('job_portal', '0009_remove_appliedjobstatus_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobstatus',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pseudos.verticals'),
        ),
    ]
