# Generated by Django 4.1.5 on 2023-04-20 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0009_alter_appliedjobstatus_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedjobstatus',
            unique_together={('applied_by', 'job')},
        ),
    ]
