# Generated by Django 4.1.5 on 2023-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0009_alter_appliedjobstatus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobstatus',
            name='is_manual_resume',
            field=models.BooleanField(default=False),
        ),
    ]
