# Generated by Django 4.1.5 on 2023-04-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0010_alter_appliedjobstatus_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedjobstatus',
            unique_together=set(),
        ),
    ]
