# Generated by Django 4.1.5 on 2023-05-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_profile_vertical_team_verticals'),
        ('job_portal', '0010_appliedjobstatus_is_manual_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobstatus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.team'),
        ),
    ]
