# Generated by Django 4.1.5 on 2023-04-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0011_remove_appliedjobstatus_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobdetail',
            name='updated_at',
        ),
    ]
