# Generated by Django 4.1.5 on 2023-05-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0013_jobdetail_created_at_jobdetail_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedjobstatus',
            unique_together=set(),
        ),
    ]
