# Generated by Django 3.2.20 on 2023-08-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0020_techstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobarchive',
            name='estimated_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobarchive',
            name='salary_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobarchive',
            name='salary_max',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobarchive',
            name='salary_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
