# Generated by Django 4.1.5 on 2023-08-22 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0021_edithistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edithistory',
            options={'default_permissions': ()},
        ),
        migrations.AlterUniqueTogether(
            name='edithistory',
            unique_together={('instance_id', 'model', 'changes', 'user')},
        ),
        migrations.AlterModelTable(
            name='edithistory',
            table='edit_history',
        ),
    ]
