# Generated by Django 4.1.5 on 2023-08-22 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20230811_1848'),
        ('job_portal', '0023_jobdetail_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='edithistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
    ]
