# Generated by Django 4.1.5 on 2023-08-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0024_edithistory_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edithistory',
            unique_together=set(),
        ),
    ]
