# Generated by Django 4.1.5 on 2023-08-23 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0025_alter_edithistory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edithistory',
            unique_together={('instance_id', 'model', 'changes', 'user')},
        ),
    ]
