# Generated by Django 4.1.5 on 2023-08-23 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0026_alter_edithistory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edithistory',
            name='changes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), size=None),
        ),
    ]
