keyword = {
    "python":
        ["Python", "Python Developer", "Data Scientist (Python)", "Python Engineer", "Python Programmer",
         "Python Software Engineer", "Python Data Analyst", "Python Automation Engineer", "Python Full Stack Developer",
         "Python Scripter", "Python Data Engineer", "Python Machine Learning Engineer", "Python Backend Developer",
         "Python Web Developer", "Python Script Developer", "Python Django Developer", "Python Flask Developer",
         "Python Artificial Intelligence Engineer", "Python Natural Language Processing Engineer",
         "Junior Python Developer", "Back End Developer", "Associate Python Developer", "Database Engineer",
         "Junior Software Developer", "Quality Assurance Engineer", "Senior Python Developer"],
    "dot net":
        [".NET Developer", ".NET Programmer", ".NET Software Engineer", ".NET Architect", ".NET Consultant",
         ".NET Technical Lead", ".NET Systems Analyst", ".NET Web Developer", ".NET Application Developer",
         ".NET Solutions Engineer", "Dot Net Core Developer", "Senior Dot Net Core Engineer",
         "Dot Net Core Software Engineer", "Dot Net Core Web Developer", "Dot Net Core Solution Architect",
         "Dot Net Core Technical Lead", "Dot Net Core Programmer", "Dot Net Core Application Developer",
         "Dot Net Core Consultant", "Dot Net Core Backend Developer", "C# Developer", "Software Engineer (C#)",
         "C# Programmer", "C# Software Developer", "C# Web Developer", "C# Software Engineer",
         "C# Application Developer", "C# Systems Developer", "C# Solutions Developer", "C# Technical Lead",
         "C# Development Team Lead", "C# Systems Analyst", "C# Back-End Developer", "C# Senior Developer",
         "C# Technical Consultant"],
    "java":
        ["Java Developer", "Senior Java Engineer", "Java Software Engineer", "Java Programmer", "Java Architect",
         "Java Lead Developer", "Java Technical Lead", "Java Web Developer", "Java Backend Developer",
         "Java Full Stack Developer", "Java Engineer", "Java Application Developer", "Java Consultant",
         "Java Technical Consultant", "Java System Engineer", "Maven", "Eclipse", "Scala", "Android Developer",
         "Spring MVC"],
    "mern":
        ["Full Stack Developer (MERN)", "MERN Stack Engineer", "MERN Web Developer", "MERN Application Developer",
         "MERN Full Stack Engineer", "MERN Software Developer", "MERN Stack Programmer",
         "MERN Web Application Developer", "MERN Full Stack Software Engineer", "MERN Application Engineer",
         "Front-end Engineer", "JavaScript Developer", "UI Developer", "Web Developer", "React.js Developer",
         "Front-end Web Developer", "JavaScript Engineer", "React Engineer", "UI Engineer.",
         "JavaScript Developer (Node.js)", "Full Stack Developer (Node.js)", "Backend Developer (Node.js)",
         "Web Developer (Node.js)", "Software Engineer (Node.js)", "Node Engineer", "Node.js Developer",
         "Server-side Developer (Node.js)", "API Developer (Node.js)", "Node.js Engineer (Full Stack)",
         "Node.js Backend Developer", "Node.js Full Stack Engineer", "Node.js API Developer",
         "Node.js Software Engineer", "Node.js Web Developer.", "MongoDB Engineer", "NoSQL Developer",
         "MongoDB Programmer", "Big Data Developer", "MongoDB Database Administrator", "MongoDB Consultant",
         "Data Engineer (MongoDB)", "MongoDB Developer - Full Stack", "MongoDB Data Analyst",
         "MongoDB Systems Engineer", "Full Stack Engineer", "Full Stack Web Developer", "Full Stack Software Engineer",
         'Full Stack Architect', "Junior Developer", "Associate Developer", "Web Development Apprentice",
         "Front End Developer", "Back End Developer", "Mobile Developer", "Senior Developer",
         "Web Development Instructor", "Web Designer", "Junior Web Designer", "Associate Web Designer",
         "Senior Web Designer", "Design Director", "Express JS", "Node Js", "MongoDB", "Javascript", "React.js",
         "express.js", "Apache", "Nginx", "Gunicorn"],
    "salesforce": ["Salesforce Administrator", "Salesforce Developer", "Salesforce Consultant",
                   "Salesforce Business Analyst", "Salesforce Project Manager",
                   "Salesforce Marketing Automation Specialist", "Salesforce Technical Architect",
                   "Salesforce Solutions Engineer", "Salesforce Sales Operations Analyst",
                   "Salesforce Technical Account Manager"],
    "Devops": ["DevOps Engineer", "Cloud Engineer", "Infrastructure Engineer", "Systems Engineer",
               "Configuration Manager", "Release Engineer", "Continuous Integration Engineer", "Automation Engineer",
               "Deployment Engineer", "Operations Engineer", "CI/CD Engineer", "Azure devops", "DevOps Engineer (CICD)",
               "CICD Engineer", "CICD Developer", "CICD Automation Engineer", "CICD Pipeline Architect",
               "CICD Operations Engineer", "CICD Infrastructure Engineer", "CICD Release Engineer", "CICD Analyst",
               "CICD Technical Lead"],
    "Database": ['Database Administrator (DBA)', "Data Analyst", "Database Engineer", "Data Architect",
                 "Database Developer", "Data Scientist", "Business Intelligence Analyst", "Data Warehouse Developer",
                 "Big Data Engineer", "Data Management Specialist", "Data Governance Analyst", "Database Consultant",
                 "Data Modeler", "Data Quality Analyst", "Data Integration Developer", "Data Security Analyst",
                 "Database Marketing Analyst", "Data Operations Analyst", "Data Warehouse Architect",
                 "Data Migration Specialist.", "Mysql", "SQL", "Postgres", "MongoDb"],
    "ui/ux": ['Database Administrator (DBA)', "Data Analyst", "Database Engineer", "Data Architect",
              "Database Developer", "Data Scientist", "Business Intelligence Analyst", "Data Warehouse Developer",
              "Big Data Engineer", "Data Management Specialist", "Data Governance Analyst", "Database Consultant",
              "Data Modeler", "Data Quality Analyst", "Data Integration Developer", "Data Security Analyst",
              "Database Marketing Analyst", "Data Operations Analyst", "Data Warehouse Architect",
              "Data Migration Specialist.", "Mysql", "SQL", "Postgres", "MongoDb"],
    "Ruby on Rails": ["Ruby on Rails Developer", "ROR Engineer", "ROR Programmer", "Ruby on Rails Software Engineer",
                      "ROR Web Developer", "Ruby on Rails Full Stack Developer", "ROR Application Developer",
                      "Ruby on Rails Systems Engineer", "ROR Solutions Developer", "Ruby on Rails Technical Lead"],
    "Data Engineer/Ml Enginner": ["Data Infrastructure Engineer", "Big Data Engineer", "Data Pipeline Engineer",
                                  "Data Warehousing Engineer", "Data Integration Engineer", "Data Management Engineer",
                                  "Data Science Engineer", "Data Solutions Engineer", "Data Automation Engineer",
                                  "Data Operations Engineer", "Machine Learning Developer",
                                  "Artificial Intelligence Engineer", "Data Scientist", "Deep Learning Engineer",
                                  "Predictive Modeling Engineer", "Computer Vision Engineer",
                                  "Natural Language Processing Engineer", "Reinforcement Learning Engineer",
                                  "Predictive Analytics Engineer", "AI Research Engineer"],
    "Data science": ["Data Analyst", "Data Engineer", "Machine Learning Engineer", "Business Intelligence Analyst",
                     "Big Data Engineer", "Data Mining Engineer", "Data Scientist", "Predictive Modeler",
                     "Data Governance Analyst", "Data Visualization Analyst", "Junior Data Scientist",
                     "Senior Data Scientist", "Big Data Analytics Consultant", "Data Science Instructor",
                     "Decision Scientist"],
    "Service Now": ["Service Desk Analyst", "IT Service Management Specialist", "Service Now Administrator",
                    "IT Operations Analyst", "Service Now Developer", "IT Support Engineer", "Service Now Consultant",
                    "IT Incident Manager", "Service Now Project Manager", "IT Service Continuity Analyst"]
}
