keyword = {
    "python": [
        "Python",
        "Python Developer",
        "Python Engineer",
        "Python Programmer",
        "Python Software Engineer",
        "Python Full Stack Developer",
        "Python Full-Stack Developer",
        "Python Scripter",
        "Python Backend Developer",
        "Python Back-end Developer",
        "Python Web Developer",
        "Python Script Developer",
        "Python Django Developer",
        "Python Flask Developer",
        "Junior Python Developer",
        "Associate Python Developer",
        "Senior Python Developer"
    ],
    "salesforce": [
        "salesforce",
        "Salesforce Administrator",
        "Salesforce Developer",
        "Salesforce Consultant",
        "Salesforce Business Analyst",
        "Salesforce Project Manager",
        "Salesforce Marketing Automation Specialist",
        "Salesforce Technical Architect",
        "Salesforce Solutions Engineer",
        "Salesforce Sales Operations Analyst",
        "Salesforce Technical Account Manager"
    ],
    "Database": [
        "database",
        "Database Administrator (DBA)",
        "Database Engineer",
        "Database Developer",
        "Data Management Specialist",
        "Data Governance Analyst",
        "Database Consultant",
        "Data Modeler",
        "Data Integration Developer",
        "Data Security Analyst",
        "Database Marketing Analyst",
        "Data Operations Analyst",
        "Data Migration Specialist.",
        "Mysql",
        "SQL",
        "NoSQL",
        "Postgres",
        "MongoDb"
    ],
    "Ruby on Rails": [
        "Ruby on Rails",
        "Ruby on Rail",
        "Ruby on Rails Developer",
        "ROR Engineer",
        "Ruby",
        "ROR Developer",
        "ROR Programmer",
        "Ruby on Rails Software Engineer",
        "ROR Web Developer",
        "Ruby on Rails Full Stack Developer",
        "ROR Application Developer",
        "Ruby on Rails Systems Engineer",
        "ROR Solutions Developer",
        "Ruby on Rails Technical Lead"
    ],
    "Ml Enginner": [
        "Machine Learning Engineer",
        "Machine Learning Developer",
        "Artificial Intelligence Engineer",
        "Python Machine Learning Engineer",
        "Python Artificial Intelligence Engineer",
        "Python Natural Language Processing Engineer",
        "Predictive Modeling Engineer",
        "Computer Vision Engineer",
        "Natural Language Processing Engineer",
        "Reinforcement Learning Engineer",
        "Predictive Analytics Engineer",
        "AI Research Engineer",
        "Director,Technical Program Management - Card Tech Machine Learning",
        "Software Engineer (AI/ML/Deep Learning)",
        "$300/1hour Paid Market Research Study for AI & Machine Learning",
        "Manager,Machine Learning Engineering (People Leader)",
        "Director, Machine Learning Engineering (Enterprise Feature Platform)",
        "Machine learning engineer",
        "Senior Machine Learning Engineer",
        "Distinguished Machine Learning Engineer- Applied Research",
        "Control Engineer at Robotics Integrator / Machine Tool Builder",
        "Principal Software Engineer,Machine Learning",
        "Senior Backend Engineer- Applied Machine Learning",
        "Determined AI - Product Manager, Machine Learning",
        "Machine Operator",
        "EDA Machine Learning Software Engineer",
        "Senior Software Engineer,Machine Learning Backend",
        "Staff Software Engineer,Machine Learning",
        "Senior Backend & Machine Learning Engineer",
        "Artificial Intelligence/Counter AI Developer",
        "Sr Software Engineer Machine Learning - Large Scale",
        "Machine Learning Architect – Engine",
        "Azure Machine Learning",
        "Computer Vision/Machine Learning Engineer (FT)",
        "Sr. Machine Learning Software Engineer (Python, Pytorch, Tensorflow)",
        "Machine Learning Chief Executive Officer",
        "Signal Processing AI/Machine Learning Engineer",
        "Head of Machine Learning Engineer",
        "Machine Learning Engineer / Data Scientist / Computational Scientist",
        "Machine Learning Engineer (ML Engineer)",
        "Junior Python / Machine Learning Engineer",
        "Junior Python /Machine Learning Engineer",
        "Software Engineer (Machine Learning, Python)",
        "Director,Technical Program Management-Card Tech Machine Learning",
        "Web Handler - Machine Operator",
        "Sr. Lead Machine Learning Engineer",
    ],
    "Data Engineering/Data Engineer": [
        "SOFTWARE ENGINEER BIG DATA",
        "Python Data Engineer",
        "Data Automation Engineer",
        "Data Operations Engineer",
        "Big Data Developer",
        "Big Data Engineer",
        "MongoDB Data Analyst",
        "Data Engineer (MongoDB)",
        "Data Mining Engineer",
        "Big Data Analytics Consultant",
        "Data Infrastructure Engineer",
        "Data Pipeline Engineer",
        "Data Warehousing Engineer",
        "Data Warehouse Developer",
        "Data Warehouse Architect",
        "Data Integration Engineer",
        "Data Management Engineer",
        "Data Solutions Engineer"
    ],
    "Data Science/Data Scientist": [
        "Data Scientist (Python)",
        "Python Data Analyst",
        "Data Scientist (TS/SCI)",
        "Data Scientist - Tableau Developer",
        "ETL Healthcare Developer/Data Scientist SQL AZURE Devops",
        "R Developer/ Data Scientist",
        "Data Scientist/Analyst",
        "Cybersecurity Analyst Levels 1-7,Data Scientist",
        "Sr. Data Scientist",
        "Data Scientist - Global Sales",
        "Data Scientist / Validation Analyst",
        "Sr. Lead Machine Learning Engineer",
        "Data Scientist,Commerce Platform – Fulfillment",
        "Data Scientist with OLAP",
        "Associate Data Scientist - Online Business Analytics",
        "Entry Level Programmer/Coder/Developer/Data Scientist/Analyst/Engineer",
        "Business Intelligence Analyst",
        "Data Governance Analyst",
        "Data Visualization Analyst",
        "Junior Data Scientist",
        "Senior Data Scientist",
        "Data Science Instructor",
        "Decision Scientist",
        "Data Science Engineer",
    ],
    "Service Now": [
        "Service Now",
        "servicenow",
        "ServiceNow Developer",
        "Service Desk Analyst",
        "IT Service Management Specialist",
        "Service Now Administrator",
        "IT Operations Analyst",
        "Service Now Developer",
        "IT Support Engineer",
        "Service Now Consultant",
        "IT Incident Manager",
        "Service Now Project Manager",
        "IT Service Continuity Analyst"
    ],
    "Android": [
        "Android",
        "Product Manager and Android Developer on W2",
        "Android Developer",
        "Android Reverse Engineer",
        "Sr Android developer",
        "Automation Test Engineer with Android/ Kotlin/ Espresso",
        "Android Developer Ref 3322",
        "Senior Backend Kotlin Engineer REMOTE Contract",
        "Manager, Software Engineering, Android",
        "Senior Android-Linux Software Engineer",
        "Senior Android Engineer",
        "Lead Android Developer",
        "Android Application Developer with Kotlin and Java development",
        "Android BSP Engineer",
        "Android Developer / iOS Developer",
        "Sr. Android Developer with strong CI/CD experience",
        "Android Malware Reverse Engineer",
        "Android Developer with Java Experience",
        "Android Developer Mid",
        "Android Developer(Onsite for CA and NC)",
        "Android Developer Mobile Apps",
        "Native Android Developer",
        "Senior Android Native Developer",
        "Kotlin Developer",
        "Embedded Android Developer",
        "PHP, VUE, Figma, Java Android, Software EXPERTS: Video Narration Tutorials",
        "Principal/ Senior Mobile Developer- iOS/Android",
        "Senior Android Developer with Machine Learning Exposure",
        "Entry LEVEL Android Developer",
        "Software Engineer Kotlin 17686",
        "Sr. Embedded Connectivity Engineer, Android OS",
        "Senior Android Engineer, XPOS",
        "Lennox - Android Developer",
        "Software Engineer II - Java/Android",
        "Android Automotive OS Developer",
        "Senior Android Engineer, Health, Cash App",
        "Android/IOS Security SDK Developer",
        "Android Audio Framework Engineer",
        "Android Firmware Developer",
        "NodeJS/Kotlin Software Engineer IV",
        "Lead Android Developer / BioTech / Pre IPO",
        "Digital Banking Mobile Developer (IOS or Android)",
        "Yahoo Finance Android Engineer",
        "Embedded Software Engineer (QNX/Wireless/Android)",
        "Android Developer-Onshore",
        "Mobility Software Engineer III - Android",
        "Mobile Developer",
        "Digital Media Buyer (Android)",
        "Principal/ Senior Mobile Developer- iOS/Android",
        "Android (Unix Shell scripting)",
        "Mobile App Developer",
        "JR Mobile App Developer",
        "Android Developer/Software/Mobile Developer/Mobile Developer/Bluetooth/Wifi/IOS Developer/IOS"
    ],
    "qa": [
        "Big Data Developer with Automation Testing (SDET)",
        "Data Quality Analyst",
        "test engineer - go",
        "Python Automation Engineer",
        "Quality Assurance Engineer",
        "Software Development Engineer - Test - Automation Testing",
        "Java Developer with Automation Testing ExperienceSenior Automation Testing",
        "Software Automation Testing Engineer",
        "Full Stack Software Engineer Leading Automation TestingLead QA Engineer",
        "Automation TestingETL Data warehouse (Database) Manual",
        "Automation TestingElectrical Engineer",
        "Automation Testing DesignSenior R&D Engineer Software",
        "Automation Testing (m/f/d)IT - Technical Test Lead Finacle-IVS",
        "Automation testingElectrical Engineer",
        "Automation Testing Design#6834#2",
        "Automation Testing(Java/C#-API",
        "Automation using Rest Assured",
        "Automation TestingPython",
        "Automation Testing (with good coding/development background)",
        "Automation Testing - Ruby",
        "Mobile Automation Testing (with good coding/development background)",
        "DevOps Automation Testing (with good coding/development background)",
        "Automation Testing with Data Migration (with good coding/devepment background)",
        "Senior QA Automation Engineer (Must Have Both Manual and Automation testing)",
        "Senior Automation / Development Engineer with Functional Testing experience, including ability to create, maintain and execute both manual and automated tests",
        "SDET Automation QA(.NET/C# Testing)",
        "Automation Engineer (Bilingual)- FrenchVulnerability and Penetration Tester",
        "Senior Automation EngineerQA Tester (Messaging System)- Financial ClientSystem Analyst :: Direct Client:: Fidelity InvestmentsTest Analyst",
        "Senior Performance Tester (W2 Only)",
        "Senior QA AnalystSoftware Quality Assurance Tester",
        "Vehicle Tester / Test Specialist - AutomationHardware Test Engineer",
        "SAP Testing Manager need in TXSDET",
        "Automation Engineer with Azure DevopsLead Performance Test EngineerTest Lead",
        "QA Tester with Mobile testing & Vehicle, Head unit TestingQA Lead",
        "Automation TesterSr. System Testing AnalystSDET",
        "Test Automation Engineer/ OnSite/ C2HSDET - Java (Onsiteinterview in Westlake, TX)",
        "QA Automation Engineer",
        "QA - ETL/DW testingRuby SDET /RSPEC, Capybara, APIs",
        "QA Automation Architect - PythonIT-Qlty Engineer/27/TEC103",
        "Mid-Level Quality Engineer",
        "Lead Quality Engineer",
        "Quality Assurance Consultant",
        "Automation Test Engineer / SDET - ONSITE - NO SPONSORSHIPS / NO 3RD PARTIES",
        "Sr. QA Automation (SELENINUM + CUCUMBER)",
        "Sr. QA Automation Engineer Quality Assurance Analyst (Device Connectivity)"
    ],
    "Dynamics": [
        "Dynamics",
        "MS Dynamics CRM Specialist",
        "MS Dynamics CRM Consultant",
        "Microsoft Dynamics CRM",
        "MS Dynamics (Marketing) Developer",
        "MS Dynamics 365 Developer",
        "PowerApps / CRM Dynamics developer",
        "Dynamics 365 CRM F&O SME",
        "DYNAMICS 365 ARCHITECT",
        "Senior MS Dynamics 365 Developer",
        "Sr. Microsoft Dynamics AX Developer",
        "Microsoft Dynamics 365 Azure Developer",
        "NYTP Requirement for MS Dynamics 365 Developer",
        "Microsoft Dynamics Consultant",
        "Sr. Power Portal Developer ( MS Dynamics 365 )",
        ".Net Core Architect or Dynamics 365",
        "MS Dynamics developer",
        "MS Dynamics NAV Developer",
        "Kaizen Dynamics",
        "Microsoft Dynamics 365 Developer/ Analyst in Trenton",
        "Dynamics F&O Architect",
        "Dynamics 365 Lead Developer with (Azure Cloud)",
        "Power Apps Developer",
        "Senior Dynamics",
        "NJDOH Microsoft Dynamics 365 Developer / Analyst",
        "MS Dynamics 365 developer CRM/CE",
        "Software Engineer III- Microsoft Dynamics",
        "Dynamics CRM Consultant (Power Automat, SSIS )",
        "Microsoft Dynamics NAV/Business Central Developer",
        "CRM MS Dynamics 365 (marketing module)",
        "Microsoft Dynamics Great Plains Developer",
        "Dynamics CE Senior Software Engineer",
        "DotNet Core Software Developer (.NET Core, Dynamics AX/ERP)",
        "Dynamics 365 CE Full Stack Developer",
        "Senior Dynamics Developer-Ann Arbor",
        "MS Dynamics CRM Tech Specialist",
        "Microsoft Dynamics 365 Functional Analyst",
        "Dynamics 365 Business Central (BC/NAV) Developer",
        "Dynamics 365 CE Solution Developer",
        "Dynamics F&O Developer",
        "MS Dynamics 365 Developer (SOAP REST API Azure - .NET)",
        "Thermodynamics Engineer Level 5",
        "Mechanical Engineer: Dynamics Analyst",
        "Dynamics GP(Great Plains) Developer",
        "Dynamics AX Developer",
        "Aerodynamics Software Tools Engineer, New Programs",
        "Business Systems Support Analyst - Microsoft Dynamics",
        "CUDA/C++ Developer, Molecular Dynamics",
        "Software Engineer III, Dynamics",
        "Software Developer (C#, ASP.NET, CRM Dynamics, SQL/SSRS)",
        "Senior Dynamics 365 Advanced Cloud Engineer – CTJ",
        "Senior Dynamics 365 Advanced Cloud Engineer",
        "Microsoft Dynamics Developer",
        "Dynamics AX"
    ],
    "flutter": [
        "Software Engineer: React.js and Flutter",
        "Lead Mobile Flutter Developer",
        "Sora Schools | Software Engineer - Flutter",
        "Sr. iOS Developer - React-Native/Flutter - On-site - RELO TO NYC",
        "Remote Senior Flutter Developer - Flutter or React Native",
        "Senior Flutter Engineer",
        "Mobile Flutter Developer - Flutter, Dart",
        "Flutter Developer (f/m/d)",
        "Lead Engineer, Flutter",
        "Flutter",
        "QA Analyst III - Dart Project",
        "Flutter Front End Developer",
        "PokerStars (Flutter) | Software Engineer (C++)",
        "iOS Developer (Swift/Flutter/React-Native)",
        "Software Engineer (Mobile/Flutter)",
        "Sr Flutter Engineer",
        "Flutter Unity mobile app developer",
        "QA Automation Engineer (Mobile/Flutter)",
        "Junior Flutter Mobile Developer",
        "Flutter Flow App Developer",
        "Remote Mobile Developer (iOS/Flutter)",
        "Senior Flutter Developer (LATAM)",
        "Cross Platform Flutter Developer",
        "Intermediate Flutter Application Tester & Developer",
        "Mobile Flutter",
        "Flutter Developer (Mid+)",
        "Flutter/Android Developer",
        "Dart / Flutter Developer (f/m/x)",
        "Flutter Engineer - Numarics Team",
        "Dev Flutter | Remoto",
        "Mobile Engineer Flutter",
        "Mobile en Flutter",
        "iOs - Flutter",
        "Cool Flutter Developer",
        "Flutter Developer - (Experience 1+year) Immediate joiner",
        "Mobile Developer (Flutter) (CPT Hybrid)",
        "Hybrid Mobile App Developer - ReactNative_Flutter",
        "Talented Flutter Developer Required",
        "Part time Flutter Developer required",
        "Experienced Flutter Programmer",
        "Trainee Flutter Developer (Leading to Job)",
        "Flutter Google Map Specialist",
        "Senior Faculty for Dart, Flutter",
        "Flutter & Android Developer",
        "Flutter Developer",
        "Encora Hiring For Software Engineer (Flutter, Android/iOS)",
        "Flutter Ui Developer",
        "Hiring Flutter/Android Developers"
    ],
    "ios": [
        "ios",
        "Sr ios developer.##w2only",
        "sr ios developers/ Architect",
        "senior software engineer",
        "ios (remote-eligible)",
        "sr ios engineer-FT  Remote",
        "senior software engineer",
        "ios (remote-eligible)",
        "mobile ios developer",
        "application architect V (ios developer)",
        ":ios developer ( remote)",
        "ios /swift developer",
        "Staff Software Engineer, iOS",
        "Engineer III - iOS - CAT",
        "IOS Developer (Only on W2) - Austin, TX / Sunnyvale, CA (Day1 Onsite)",
        "Urgent job opening for iOS developer in Fremont, CA - Onsite From day 1 - Contract",
        "iOS Native Developer",
        "IOS Developer (Onsite Fremont, CA or Charlotte/NC)",
        "iOS Developer with News and Sports Application Experience",
        "iOS Developer (San Francisco, CA | Charlotte, NC)",
        "IOS Developer Malvern PA(Onsite)",
        "Need iOS developer in Austin, TX (Day one onsite)",
        "SENIOR IOS/OS CROSS PLATFORM DEVELOPER",
        "iOS Developer in Fremont, CA, Columbus, OH, New York, NY (2-3days onsite/week) locations",
        "iOS Developer in San Francisco, CA (Onsite & Face to Face Interview)",
        "iOS Developer,TBD",
        "Mobile iOS Engineer - Marketplace for Operators",
        "Onsite // IOS Developer (Swift, Native, API)",
        "Principal iOS Software Engineer (Palo Alto) - Direct Hire [Remote]",
        "iOS Developer MIN 9 Years Experience",
        "Senior iOS Developer / Boston, MA , 6 + Months Contract",
        "Entry level ios Developer",
        "Mobile App Developer (iOS) $80-110k 3D Imaging",
        "iOS SpringBoard Engineer - Wallpaper",
        "IOS Developer- IRVING, TX",
        "Product Manager IOS/Browser/Apple Store",
        "Princ iOS Software Apps Engineer",
        "MTS1 iOS Software Engineer, Motors",
        "MacOS/iOS Software Engineer- 100% REMOTE, Swift, Objective-C",
        "iOS Developer - Fintech startup - Onsite in Irvine",
        "Mac OS/iOS Developer, Wireless",
        "iOS Developer || Plano, TX Day 1 onsite",
        "iOS Display Driver Engineer",
        "iOS Developer (remote in MI, CA or NY/NJ)",
        "Staff iOS Engineer, Navigation",
        "Senior iOS Developer / Boston, MA , 6 + Months Contract",
        "Staff iOS Engineer, Platforms Core",
        "REMOTE Mobile App Developer (iOS) $80-110k!",
        "iOS Mobile Developer - Garmin Pilot App",
        "Ios Developer (Remote In Mi, Ca Or Ny/Nj)",
        "iOS Engineer, Mapping",
        "iOS Developer, Location:Plano, TX C2C, 12months+ Role",
        "iOS Developer -Day one onsite Fremont CA (ONLY 10+YRS NEEDED)",
        "Mobile Software Engineer - iOS - Tysons"
    ],
    "UI/UX": [
        "Senior Game Designer (Remote)",
        "WordPress Website Designer (Contract)",
        "Frontend Developer",
        "Front-end Web Developer",
        "Front-end Engineer",
        "UX Designer(javascript)",
        "UI Developer",
        "UI/UX designer/developer",
        "Frontend",
        "Lead (AEM) Adobe Experience Manager Developer",
        "UX Engineer",
        "UI Engineer.",
        "Adobe Target Developer",
        "UX Researcher",
        "Sr. UX/UI Designer",
        "Web Designer",
        "Junior Web Designer",
        "Associate Web Designer",
        "Senior Web Designer",
        "UI / UX Designer with Drupal",
        "Design System Frontend Developer",
        "Frontend Software Developer",
        "Sharepoint Learning site designer",
        "Instructional Designer",
        "Frontend Developer - hybrid onsite",
        "Instructional Designer III",
        "User Experience Designer",
        "Instructional Designer - Remote | WFH",
        "UI Designe",
        "Frontend Web Software Engineer",
        "Senior Frontend Developer",
        "Software Developer - Adobe",
        "PHP -Frontend Developer-Remote",
        "Frontend/ UI Developer",
        "Frontend Engineer",
        "Sr. Front-End Engineer, UX Platform - Foundation",
        "Senior Remote Frontend Engineer",
        "Frontend Software Engineer",
        "Software Engineer - Frontend L2",
        "Software Engineer - Frontend/UI",
        "Learning Designer I",
        "Frontend Web Software Engineer",
        "User Experience Designer (only local to IL)",
        "Adobe Analytics Analyst",
        "Adobe Sign Form Developer",
        "Adobe Analytics/CJA Developer",
        "Sharepoint Designer",
        "UX Designer",
        "Design Director",
        "Java Frontend Developer",
        "Looking for front end developer with knowledge and some experience in React js and React",
        "UX Design/Developer",
        "Developer - UX Design/Developer",
        "Quadient Inspire Developer / Designer",
        "CW Jr Frontend Developer",
        "Enterprise Architects (Digital Expert)(Frontend/React+Integration/Mulesoft)",
        "Vue.js Frontend Developer",
        ".NET Frontend Developer With VUE- JS",
        "React.JS Developer/Frontend Developer",
        "SharePoint Designer/VueJS Front End Developer",
        "Front End Developer",
        "UX Researcher IV ***W2",
        "UX Research Assistant III",
        "SharePoint Designer - W2 role",
        "Adobe AEM Developer",
        "Adobe Workfront Developer",
        "Lead UX Designer",
        "UX Researcher - Quantitative",
        "Adobe Experience Manager Developer",
        "UX-UI Designer",
        "NO C2C-Remote-Instructional Designer",
        "User Interface Designer"
    ]
}

languages = {
    "Service Now": [
        "service now",
        "service-now",
        "servicenow"
    ],
    "qa": [
        "SDET",
        "qa",
        "sqa",
        "api test",
        "test api",
        "selenium test",
        "performance engineer",
        "performance test",
        "test",
        "testing",
        "Automation Test",
        "Test Automation",
        "Quality Assurance",
        "Quality Assurance Consultant",
        "testing",
        "qa engineer",
        "qa test",
        "quality engineer",
        "regression test",
        "unit test",
        "blackbox test",
        "whitebox test",
        "manual test",
        "api testing",
        "software test",
        "software quality",
        "quality engineer",
        "quality",
        "bug",
        "test engineer",
        "test automation",
        "qa automation",
        "qa manual",
    ],
    "Ml Enginner": [
        "ai ml",
        "Ml Enginner",
        "ml data engineer",
        "Machine Learning",
        "Machine Learn",
        "Deep Learning Engineer",
        "NLP",
        "Scikit-learn",
        "Scikit learn",
        "Keras",
        "PyTorch",
        "image process",
        "image learn",
        "Natural Language",
        "Natural Language Processing",
        "AI Research",
        "ML Research",
        "Predictive Modeler",
        "Computer Vision",
        "AI/ML",
        "AI ML",
        "OpenCV",
        "mlpack",
        "ml.net",
        "Artificial Neural Network",
        "Torch",
        "Text Mining",
        "Text Classification",
        "Image-Based",
        "Machine Vision",
        "Sentiment Analysis",
        "Reinforcement Learn",
        "Voice Classification",
        "Artificial Intelligence",
    ],
    "Data Engineering/Data Engineer": [
        "Big Data",
        "BigData",
        "ETL developer",
        "ETL Data Developer",
        "ETL Data",
        "ETL Engineer",
        "Data Engineering",
        "Data Engineer",
        "Data Solutions",
        "Data Warehouse",
        "Data Architect",
        "Data Mining",
    ],
    "Data Science/Data Scientist": [
        "Data Science",
        "pandas",
        "Data Analyst",
        "Data Scientist",
        "Data Visualization",
        "Data Visualize",
        "Tabeleau",
        "Matplotlib",
    ],
    "blockchain": [
        "BIPs",
        "Bitcoin",
        "Block",
        "Block Height",
        "Block Reward",
        "Blockchain",
        "Blockchain 2.0",
        "Blockchain Architecture",
        "Blockchain Development",
        "Blockchain Node",
        "Byzantine Fault Tolerance",
        "Certificate Authority",
        "Closed Source",
        "Coin",
        "Consensus",
        "Consortium",
        "Corda",
        "Crypto",
        "Cryptocurrency",
        "DApp",
        "DLT",
        "DeFi",
        "Decentralization",
        "Decentralized Autonomous Organization",
        "Decryption",
        "Directed Acyclic Graph",
        "Double Spending",
        "EIPs",
        "EWASM",
        "Encryption",
        "Ethereum",
        "Ethereum Enterprise Alliance",
        "Ethereum Platform",
        "Ethereum Virtual Machine",
        "Ethers.js",
        "Genesis Block",
        "Gossip Protocol",
        "Hash Collision",
        "Hash Function",
        "Hashrate",
        "Hyperledger Fabric",
        "ICOs",
        "Immutability",
        "Mainnet",
        "Merkle Root",
        "Merkle Tree",
        "Metaverse",
        "Mining",
        "NFT",
        "Non-Fungible Token",
        "Peer to Peer",
        "Private Blockchain",
        "Private Key",
        "Proof of Stake",
        "Proof of Work",
        "Public Blockchain",
        "Public Key",
        "Public Key Infrastructure",
        "Ring Signature",
        "Scalability",
        "Secure Hash Algorithm",
        "Simple Agreement for Future Tokens",
        "Smart Contract",
        "SmartContract",
        "Smart contracts",
        "Solana",
        "SolidJS",
        "Solidity",
        "Solidity/Ethereum",
        "Stablecoins",
        "Tangle",
        "Testnet",
        "Token",
        "Tokenization",
        "Transaction",
        "Transaction Pool",
        "Trustless",
        "Turing Complete",
        "UTXO",
        "Wallet",
        "Web3.js",
        "Zero-Knowledge Proof",
        "blockchain ecosystem",
        "cryptography",
        "cypher",
        "web3"
    ],
    "salesforce": [
        "salesforce",
        "sales force",
        "salesforce crm",
        "salesforce crm developer"
    ],
    "Dynamics": [
        "dynamics",
        "dynamics 365",
        "dynamics-365",
        "dynamics365",
        "ms-dynamics",
        "D365",
        "ms dynamics",
        "ms-dynamics",
    ],
    "flutter": [
        "flutter",
        "dart"
    ],
    "PHP": [
        "cakephp",
        "php/laravel",
        "magento",
        "wordpress",
        "yii",
        "symphony",
        "lamp stack",
        "codeigniter",
        "laravel/symfony",
        "laravel",
        "php8/laravel8",
        "livewire",
        "lamp",
        "magento 2",
        "alpinejs",
        "php"
    ],
    "Python": [
        "python",
        "django",
        "full stack django developer",
        "full stack python developer",
        "python web developer",
        "flask",
        "fast api",
        "fastapi",
        "fast-api",
        "python developer",
        "sqlalchemy",
    ],
    "React Native": [
        "react native",
        "Lead Mobile Developer (React Native)",
        "Sr React Native Developer",
        "Fullstack Developer (React Native, Node.js, Typescript) - Remote",
        "React Native Mobile Developer/Architect",
        "React & React Native Frontend Developer - Remote",
        "React Native developer",
        "Mobile Developer-React Native",
        "React Native - Senior Developer (Hybrid Mobile Developer React Native)",
        "Mobile Developer React Native",
        "Senior React Native Developer (Remote)",
        "Senior React Native Engineer",
        "Javascript+React Native Engineer",
        "React Native Developer (Hybrid Mobile Developer) - Onsite",
        "SR React Native Developer (Hybrid Mobile Developer) - Onsite",
        "React Native Mobile Developer",
        "Lead React Native Developer (Remote)",
        "Remote Senior React Native -",
        "Lead React Native Developer (Remote)",
        "Senior React Native Developer - Flexible Hybrid - Chicago",
        "Remote Senior Flutter Developer - Flutter or React Native",
        "Remote Senior React Native Developer -",
        "Mobile Developer  React Native",
        "Software Engineer (Java, React Native)",
        "Mobile React Native Developer",
        "Senior Software Engineer, React Native",
        "React Native - Senior Developer",
        "Remote Senior React Native Developer - React Native, Expo, REACT",
        "Mobile Software Engineer (React Native/iOS)",
        "100% Remote - Senior React Native Developer",
        "Batelle - Sr React Native Developer - Direct Hire [Remote]",
        "Hybrid Mobile Developer- React Native",
        "Sr. Mobile React Native Developer",
        "Senior React Native Applications",
        "Senior Mobile React Native Developer",
        "Mobile Developer - Flutter or React Native",
        "Senior React Native Applications Developer",
        "React Native Full Stack Developer",
        "Senior Mobile App Developer - React Native (Remote, US)",
        "React Native Developer a Front-end, Node, Typescript a FULLY REMOTE WORK 39728",
        "React JS Developer Mid(React Native,IOS,Android,UI)",
        "Looking for front end developer with knowledge and some experience in React js and React Native, Node.js.",
        "Mobile Developer--React Native",
        "Staff/Principal Mobile UI Engineer (React Native)",
        "Tech Lead - Full stack (React Native)",
        "Mobile Developer a React Native | Alameda, California (onsite) | C2C |",
        "Software Developer - Mobile / React Native",
        "React Native Software Engineer - Sports - Hybrid",
        "Android iOS React Native Engineer for next generation products"
    ],
    "mern": [
        "mern",
        "mean",
        "mevn",
        "js developer",
        "Full Stack Developer (MERN)",
        "MERN Stack Engineer",
        "MERN Web Developer",
        "MERN Application Developer",
        "MERN Full Stack Engineer",
        "MERN Full-Stack Engineer",
        "MERN Software Developer",
        "MERN Stack Programmer",
        "MERN Web Application Developer",
        "MERN Full Stack Software Engineer",
        "MERN Full-Stack Software Engineer",
        "MERN Application Engineer",
        "JavaScript Developer",
        "React.js Developer",
        "JavaScript Engineer",
        "React Engineer",
        "JavaScript Developer (Node.js)",
        "Full Stack Developer (Node.js)",
        "Backend Developer (Node.js)",
        "Web Developer (Node.js)",
        "Software Engineer (Node.js)",
        "Node Engineer",
        "Node.js Developer",
        "Server-side Developer (Node.js)",
        "API Developer (Node.js)",
        "Node.js Engineer (Full Stack)",
        "Node.js Engineer (Full-Stack)",
        "Node.js Backend Developer",
        "Node.js Back-end Developer",
        "Node.js Full Stack Engineer",
        "Node.js Full-Stack Engineer",
        "Node.js API Developer",
        "Node.js Software Engineer",
        "Node.js Web Developer.",
        "Node.js Web-Developer.",
        "MongoDB Engineer",
        "NoSQL Developer",
        "MongoDB Programmer",
        "MongoDB Database Administrator",
        "MongoDB Consultant",
        "MongoDB Developer - Full Stack",
        "MongoDB Systems Engineer",
        "Senior Software Engineer - Frontend/React (Remote)",
        "Express JS",
        "Node Js",
        "MongoDB",
        "React",
        "ReactJS",
        "Node",
        "Nodejs",
        "Javascript",
        "React.js",
        "express.js"
    ],
    "JavaScript": [
        "javascript",
        "gastsbyjs",
        "materialui",
        "react/redux",
        "mapbox",
        "express",
        "backbone.js",
        "potractor",
        "nest.js",
        "react.js",
        "node",
        "vue",
        "nest",
        "requirejs",
        "featherjs",
        "nestjs",
        "knockoutjs",
        "vue.js",
        "cssinjs",
        "angular",
        "nodejs",
        "angular",
        "express.js",
        "yarn",
        "angular 10",
        "react",
        "nuxt.js",
        "angular",
        "angularjs",
        "hapi.js",
        "react js",
        "socket.io",
        "preact",
        "recoil",
        "node",
        "robot",
        "angular12",
        "ionic",
        "react hooks",
        "nuxt",
        "gatsbyjs",
        "npm",
        "npx",
        "angular2",
        "angular8+",
        "javascript developer",
        "ramda js",
        "websockets",
        "nuxtjs",
        "stimulusjs",
        "recoil.js",
        "proctor",
        "espresso",
        "webdriver.io",
        "angular.js",
        "pyramid",
        "redux.js",
        "reactjs",
        "leaflet",
        "backbonejs",
        "ngrx",
        "redux",
        "primeng",
        "sails.js",
        "ractive.js",
        "cosmjs",
        "nextjs",
        "next.js",
    ],
    "Java": [
        "jpm",
        "j2ee",
        "java",
        "core java",
        "javase",
        "java ee",
        "java se",
        "hibernate",
        "java8",
        "servlets",
        "spring",
        "jpa",
        "javaee",
        "rxjava",
        "jsp",
        "junit",
        "gradle",
        "java developer",
        "maven",
        "Java Developer",
        "Senior Java Engineer",
        "Java Software Engineer",
        "Java Programmer",
        "Java Architect",
        "Java Lead Developer",
        "Java Technical Lead",
        "Java Web Developer",
        "Java Backend Developer",
        "Java Full Stack Developer",
        "Java Full-Stack Developer",
        "Java Engineer",
        "Java Application Developer",
        "Java Consultant",
        "Java Technical Consultant",
        "Java System Engineer",
        "Maven",
        "Eclipse",
        "Scala",
        "Spring MVC",
        "Netbeans"
    ],
    "Devops": [
        "DevOps Engineer",
        "Cloud Engineer",
        "Dev Ops",
        "cloud software",
        "cloud/backend",
        "cloud",
        "cloud software engineer",
        "devops",
        "azure",
        "CICD",
        "devops developer",
        "Cloud Developer",
        "cloud developer - go",
        "devops engineer - go",
        "Infrastructure Engineer",
        "Systems Engineer",
        "Configuration Manager",
        "Release Engineer",
        "Continuous Integration",
        "aws",
        "Amazon Web Services",
        "Deployment",
        "Continuous Integration Engineer",
        "Deployment Engineer",
        "Operations Engineer",
        "CI/CD Engineer",
        "Azure devops",
        "DevOps Engineer (CICD)",
        "devops engineer - ruby",
        "CICD Engineer",
        "CICD Developer",
        "CICD Automation Engineer",
        "CICD Pipeline Architect",
        "CICD Operations Engineer",
        "CICD Infrastructure Engineer",
        "CICD Release Engineer",
        "CICD Analyst",
        "CICD Technical Lead",
        "Apache",
        "Nginx",
        "Gunicorn"
    ],
    "Ruby on Rails": [
        "Ruby on Rail",
        "ruby-on-rails",
        "ruby",
        "ror developer",
        "ror engineer",
        "kql",
        "ruby architect",
        "ruby software engineer",
        "turbo",
        "frontend developer - ruby",
        "ruby consultant",
        "sidekiq",
        "rails",
        "capybara",
        "full stack developer - ruby",
        "ruby web developer",
        "hotwire",
        "database developer - ruby",
        "ruby developer",
        "minitest",
        "ruby technical lead",
        "testrail",
        "ruby programmer",
        "ruby on rails developer",
        "ruby systems engineer",
        "backend developer - ruby",
        "rspec",
        "test engineer - ruby",
        "ruby/rails",
        "wireframes"
    ],
    "Go/Golang": [
        "golang",
        "Go/Golang",
        "microservices developer - go",
        "database developer - go",
        "distributed systems engineer - go",
        "distributed systems",
        "go systems engineergo developer",
        "go engineer",
        "full stack developer - go",
        "go developer",
        "golang programmer",
        "software engineer - go",
        "go web",
        "go web developer",
        "api developer - go"
    ],
    "C#/Dot Net": [
        "c#",
        "C# Dot Net",
        "unity",
        ".net",
        ".net core",
        "asp",
        "sql server",
        "xamarin.forms",
        "xamarin",
        "asp.net core",
        "asp.net",
        "netsuite development",
        "blaserc# developer",
        "wpf",
        "dot net",
        "dotnet",
        ".NET Developer",
        ".NET Full Stack",
        ".NET Full-Stack",
        ".NET Programmer",
        ".NET Software Engineer",
        ".NET Architect",
        ".NET Consultant",
        ".NET Technical Lead",
        ".NET Systems Analyst",
        ".NET Web Developer",
        ".NET Web-Developer",
        ".NET Application Developer",
        ".NET Solutions Engineer",
        "Dot Net Core Developer",
        "Senior Dot Net Core Engineer",
        "Dot Net Core Software Engineer",
        "Dot Net Core Web Developer",
        "Dot Net Core Solution Architect",
        "Dot Net Core Technical Lead",
        "Dot Net Core Programmer",
        "Dot Net Core Application Developer",
        "Dot Net Core Consultant",
        "Dot Net Core Backend Developer",
        "C# Developer",
        "Software Engineer (C#)",
        "C# Programmer",
        "C# Software Developer",
        "C# Web Developer",
        "C# Web-Developer",
        "C# Software Engineer",
        "C# Application Developer",
        "C# Systems Developer",
        "C# Solutions Developer",
        "C# Technical Lead",
        "C# Development Team Lead",
        "C# Systems Analyst",
        "C# Back-End Developer",
        "C# Senior Developer",
        "C# Technical Consultant",
    ],
    "C/C++": [
        "c developer",
        "c engineer",
        "c++ engineer",
        "c/c++ engineer",
        "c / c++ engineer",
        "c++ developer",
        "c/c++ developer",
        "c / c++ developer",
        "c++ program",
        "c program",
        "c/c++ program",
        "c / c++ program",
        "embedded c",
        "data structures",
        "opengl c",
        "winapi",
        "3d max",
        "argocd",
        "unreal engine",
        "linux kernel",
        "c++",
        "autocad",
        "blender3d",
        "c robotics"
    ],
    "ios": [
        "ios",
        "ios developer",
        "core data",
        "uikit",
        "swift",
        "cocoa touch",
        "xcode",
        "arkit",
        "objective c"
    ],
    "Android": [
        "android",
        "kotlin"
    ],
    "UI/UX": [
        "ui/ux",
        "front end",
        "front-end",
        "ui designer",
        "ui developer",
        "ux designer",
        "ux developer",
        "visual designer",
        "interaction designer",
        "product designer",
        "user researcher",
        "user experience researcher",
        "information architect",
        "front-end developer",
        "mobile designer",
        "web designer",
        "digital designer",
        "graphic designer",
        "ui/ux developer",
        "ui/ux engineer",
        "ui/ux lead",
        "ui/ux manager",
        "ux writer",
        "ui/ux consultant",
        "ui/ux analyst",
        "sr. ux",
        "designer",
        "senior ux",
        "junior ux",
        "sr. user experience",
    ],
    "Networking": [
        "network engineer",
        "network administrator",
        "network technician",
        "network analyst",
        "networking",
        "network architect",
        "network security engineer",
        "network operations center (noc) technician",
        "network support specialist",
        "wireless network engineer",
        "voip engineer",
        "network deployment engineer",
        "network solutions architect",
        "network performance analyst",
        "network planning engineer",
        "network project manager",
        "network consultant",
        "cloud network engineer",
        "cloud network",
        "network automation engineer",
        "network integration engineer",
        "network systems engineer"
    ],
    "Database": [
        "database",
        "sql",
        "postgres",
        "mongo",
        "prisma",
        "pl/sql",
        "ms sql",
        "mariadb",
        "postgis",
        "mssql",
        "dbt",
        "solaris",
        "sqlite",
        "dynamodb",
        "sequelize.js",
        "kdb+",
        "microsoft sql server",
        "database architecture",
        "neo4j",
        "oracle",
        "queries",
        "postgate",
        "sql server administration",
        "relational databases",
        "indexeddb",
        "mysql/postgresql",
        "mysql/mongodb",
        "ssrs",
        "postgresql",
        "redis",
        "mangodb",
        "postgres",
        "sql server",
        "database design",
        "cockroachdb",
        "crafting sqls",
        "mysql",
        "arangodb",
        "rdbms",
        "knex.js",
        "microsoft sql",
        "t-sql",
        "ssis",
        "cassandra",
        "ms-sql"
    ],
}

regular_expressions = [
    {
        'tech_stack': 'Ruby on Rails',
        'exp': '(?i)(^|\W)(ror)(\W|$)'
    },
    {
        'tech_stack': 'UI/UX',
        'exp': '(?i)(^|\W)(ux|ui)(\W|$)'
    },
    {
        'tech_stack': 'Ml Enginner',
        'exp': '(?i)(^|\W)(ai|ml|machine learn)(\W|$)'
    },
    {
        'tech_stack': 'Go/Golang',
        'exp': '(?i)(^|\W)(go|golang)(\W|$)'
    }
]

developer = [
    "api developer",
    "computer engineer",
    "computer science",
    "computer developer",
    "computer",
    "associate back-end dev",
    "associate back-end developer",
    "associate back-end engineer",
    "associate backend dev",
    "associate backend developer",
    "associate backend engineer",
    "associate developer",
    "associate se",
    "associate software engineer",
    "associate web developer",
    "associate web-developer",
    "backend",
    "back-end",
    "back end developer",
    "back-end api developer",
    "back-end coder",
    "back-end dev",
    "back-end developer",
    "back-end programmer",
    "back-end web developer",
    "back-end web programmer",
    "back-end web-developer",
    "back-end web-programmer",
    "backend api developer",
    "backend coder",
    "backend dev",
    "backend developer",
    "backend programmer",
    "backend web developer",
    "backend engineer",
    "coder",
    "developer",
    "full stack",
    "full-stack",
    "frontend engineer",
    "full stack architect",
    "full stack developer",
    "full stack engineer",
    "full stack se",
    "full stack software developer",
    "full stack software engineer",
    "full stack web developer",
    "full-stack architect",
    "full-stack developer",
    "full-stack engineer",
    "full-stack se",
    "full-stack software developer",
    "full-stack software engineer",
    "full-stack software-developer",
    "full-stack software-engineer",
    "full-stack web developer",
    "full-stack web-developer",
    "junior api developer",
    "junior back-end developer",
    "junior backend developer",
    "junior backend-developer",
    "junior dev",
    "junior developer",
    "junior se",
    "junior software developer",
    "junior software engineer",
    "junior software-developer",
    "junior software-engineer",
    "junior web developer",
    "junior web-developer",
    "junior-dev",
    "junior-developer",
    "junior-se",
    "lead api developer",
    "lead se",
    "lead software devloper",
    "lead software engineer",
    "lead web developer",
    "lead web engineer",
    "lead web-developer",
    "lead web-engineer",
    "programmer",
    "programmers",
    "programming",
    "senior api developer",
    "senior back-end dev",
    "senior back-end developer",
    "senior backend developer",
    "senior dev",
    "senior developer",
    "senior se",
    "senior software developer",
    "senior software engineer",
    "senior software-developer",
    "senior software-engineer",
    "senior web developer",
    "senior web-developer",
    "soft",
    "software",
    "software developer",
    "software engineer",
    "software engineering",
    "software web developer",
    "software web-developer",
    "software-developer",
    "software-engineer",
    "software-engineering",
    "web coder",
    "web dev",
    "web developer",
    "web development apprentice",
    "web development instructor",
    "web programmer",
    "web programming",
    "web-coder",
    "web-dev",
    "web-developer",
    "web-development instructor",
    "web-programmer",
    "web-programming"
]
