# Generated by Django 4.1.5 on 2024-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaskscrapper', '0002_scraperrunningstatus_status_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapersLoopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_source', models.CharField(blank=True, max_length=250, null=True)),
                ('loop_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='scraperrunningstatus',
            name='status_type',
        ),
    ]
