# Generated by Django 4.1.5 on 2023-02-16 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_teammanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammanagement',
            name='reporting',
            field=models.ManyToManyField(related_name='repoting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
