# Generated by Django 4.1.5 on 2023-02-13 08:22

from django.db import migrations
import settings.utils.model_fields.email


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_unique_together_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=settings.utils.model_fields.email.LowercaseEmailField(max_length=254, unique=True),
        ),
    ]
