# Generated by Django 4.1.5 on 2023-03-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
