# Generated by Django 4.1.5 on 2023-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0012_alter_education_end_date_alter_education_start_date'),
        ('authentication', '0015_team_pseudos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pseudos',
        ),
        migrations.AddField(
            model_name='team',
            name='verticals',
            field=models.ManyToManyField(related_name='verticals', to='pseudos.verticals'),
        ),
    ]
