# Generated by Django 4.1.5 on 2023-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0012_alter_education_end_date_alter_education_start_date'),
        ('authentication', '0016_remove_team_pseudos_team_verticals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vertical',
            field=models.ManyToManyField(blank=True, related_name='vertical', to='pseudos.verticals'),
        ),
        migrations.AlterField(
            model_name='team',
            name='verticals',
            field=models.ManyToManyField(blank=True, related_name='verticals', to='pseudos.verticals'),
        ),
    ]
