# Generated by Django 4.1.5 on 2023-03-22 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_based', models.BooleanField(default=False)),
                ('interval_based', models.BooleanField(default=False)),
                ('time', models.TimeField(null=True)),
                ('interval', models.IntegerField(blank=True, default=0, null=True)),
                ('interval_type', models.CharField(blank=True, max_length=100, null=True)),
                ('job_source', models.CharField(default='', max_length=100)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
