# Generated by Django 4.1.5 on 2023-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0003_jobsourcequery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsourcequery',
            name='job_source',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
