# Generated by Django 4.1.5 on 2023-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0004_alter_jobsourcequery_job_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulersync',
            name='running',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
