# Generated by Django 4.1.5 on 2023-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0005_alter_schedulersync_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersync',
            name='job_source',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schedulersync',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
