# Generated by Django 4.1.5 on 2023-04-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0006_schedulersync_job_source_alter_schedulersync_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_source', models.CharField(default='', max_length=250)),
                ('total_jobs', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
