# Generated by Django 4.1.5 on 2023-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0008_allsyncconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersync',
            name='type',
            field=models.CharField(default='instant', max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='schedulersync',
            unique_together={('job_source', 'type')},
        ),
    ]
