# Generated by Django 4.1.5 on 2023-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0009_schedulersync_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulersync',
            name='job_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
